#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
    CREATE USER $GEOSERVER_PSQL_USER WITH LOGIN PASSWORD '$GEOSERVER_PSQL_PASSWORD';
    CREATE DATABASE $GEOSERVER_PSQL_USER WITH OWNER $GEOSERVER_PSQL_USER;
EOSQL
