# Generated by Django 4.2.14 on 2024-08-06 16:11

from django.db import migrations, models
import volume_api_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DEMFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=volume_api_app.models.get_dem_file_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoTIFFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=volume_api_app.models.get_geotiff_file_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GLBMesh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=volume_api_app.models.get_glb_file_path),
                ),
                (
                    "data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=volume_api_app.models.get_glb_json_path,
                    ),
                ),
            ],
            options={
                "verbose_name": "GLB Mesh",
                "verbose_name_plural": "GLB Meshes",
            },
        ),
        migrations.CreateModel(
            name="OBJMesh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=volume_api_app.models.get_obj_file_path),
                ),
                (
                    "data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=volume_api_app.models.get_obj_json_path,
                    ),
                ),
            ],
            options={
                "verbose_name": "OBJ Mesh",
                "verbose_name_plural": "OBJ Meshes",
            },
        ),
        migrations.CreateModel(
            name="PLYMesh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=volume_api_app.models.get_ply_file_path),
                ),
                (
                    "data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=volume_api_app.models.get_ply_json_path,
                    ),
                ),
            ],
            options={
                "verbose_name": "PLY Mesh",
                "verbose_name_plural": "PLY Meshes",
            },
        ),
        migrations.CreateModel(
            name="PointCloudMesh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=volume_api_app.models.get_pointcloud_file_path
                    ),
                ),
                (
                    "data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=volume_api_app.models.get_pointcloud_json_path,
                    ),
                ),
            ],
            options={
                "verbose_name": "Point Cloud Mesh",
                "verbose_name_plural": "Point Cloud Meshes",
            },
        ),
    ]
