# Generated by Django 5.0.7 on 2024-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volume_api_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="URLImageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("url", models.TextField()),
            ],
        ),
    ]
