# Generated by Django 5.0.7 on 2024-08-02 13:27

import volume_api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volume_api_app", "0002_urlimagefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="file",
            field=models.FileField(upload_to=volume_api_app.models.get_image_file_path),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="urlimagefile",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
