# Generated by Django 4.2.14 on 2024-08-02 15:11

from django.db import migrations, models
import volume_api_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("volume_api_app", "0003_alter_imagefile_file_alter_imagefile_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoTIFFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=volume_api_app.models.get_geotiff_file_path
                    ),
                ),
            ],
        ),
    ]
