# Generated by Django 4.2.14 on 2024-08-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volume_api_app", "0004_geotifffile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageFile",
        ),
        migrations.DeleteModel(
            name="URLImageFile",
        ),
    ]
