# Generated by Django 4.2.14 on 2024-08-05 07:47

from django.db import migrations, models
import volume_api_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("volume_api_app", "0007_demfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="glbmesh",
            name="data",
            field=models.FileField(
                default="", upload_to=volume_api_app.models.get_glb_json_path
            ),
            preserve_default=False,
        ),
    ]
