# Generated by Django 4.2.14 on 2024-08-06 03:44

from django.db import migrations, models
import volume_api_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("volume_api_app", "0008_glbmesh_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glbmesh",
            name="data",
            field=models.FileField(
                blank=True, null=True, upload_to=volume_api_app.models.get_glb_json_path
            ),
        ),
    ]
